name: Deploy MultiK8s
on:
  push:
    branches:
      - master

env:
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t lightyagami474/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true lightyagami474/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: multi-338920

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t lightyagami474/multi-client-k8s-gh:latest -t lightyagami474/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t lightyagami474/multi-server-k8s-gh:latest -t lightyagami474/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t lightyagami474/multi-worker-k8s-gh:latest -t lightyagami474/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push lightyagami474/multi-client-k8s-gh:latest
          docker push lightyagami474/multi-server-k8s-gh:latest
          docker push lightyagami474/multi-worker-k8s-gh:latest

          docker push lightyagami474/multi-client-k8s-gh:${{ env.SHA }}
          docker push lightyagami474/multi-server-k8s-gh:${{ env.SHA }}
          docker push lightyagami474/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=lightyagami474/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=lightyagami474/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=lightyagami474/multi-worker-k8s-gh:${{ env.SHA }}
